spring.application.name=gateway
server.port=8084



#Eureka
#To register this as a client, what propertise do I need
eureka.client.serviceUrl.defaultZone=http://servicereg:8761/eureka/
#url used by microservice to register as client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#true for both because we need to register with eureka and fetch the registry

#Zipkin
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0

#Gatway
spring.cloud.gateway.server.webflux.routes[0].id=company-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://company:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/companies/**

spring.cloud.gateway.server.webflux.routes[1].id=job-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://job:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/jobs/**

spring.cloud.gateway.server.webflux.routes[2].id=review-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://review:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/reviews/**


#Configure for eureka
#eureka server and pointed to server and pointed to path
# we can access it on localhost:8084/eureka/main
# no need to change path for other microservices but we needed to change path for it
spring.cloud.gateway.server.webflux.routes[3].id=eureka-server
spring.cloud.gateway.server.webflux.routes[3].uri=http://servicereg:8761
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/eureka/main
spring.cloud.gateway.server.webflux.routes[3].filters[0]=SetPath=/

spring.cloud.gateway.server.webflux.routes[4].id=eureka-server-static
spring.cloud.gateway.server.webflux.routes[4].uri=http://servicereg:8761
spring.cloud.gateway.server.webflux.routes[4].predicates=Path=/eureka/**

# Logging
logging.level.root=info
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway = TRACE




